apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx01
    runtime: python
    env: practise
    created_date: 26-06-2024
  name: nginx01
spec:
  containers:
  - image: nginx
    name: nginx01
