apiVersion: v1
kind: Pod
metadata:
  name: request-limit01
spec:
  containers:
  - name: nginx01
    image: nginx
    resources:
      requests:
        memory: "640Mi"
        cpu: "5"
      limits:
        memory: "1280Mi"
        cpu: "1"