apiVersion: v1
kind: Pod
metadata:
  name: secret05
spec:
  containers:
  - name: nginx-container
    image: nginx
    env:
    - name: Organization_Password
      valueFrom:
        secretKeyRef:
          name: secret03
          key: root-password
    - name: Organization_token
      valueFrom:
        secretKeyRef:
          name: secret03
          key: token
  restartPolicy: Never
