apiVersion: v1
kind: Secret
metadata:
  name: secret04
type: Opaque
stringData: 
 config.yaml: |-
   root-password: root@123
   token: algonox_1234567
# Strdata:
#   root-password: cm9vdEAxMjM=
#   token: YWxnb25veF8xMjM0NTY=

