apiVersion: v1
kind: Pod
metadata:
  name: secret05
spec:
  containers:
  - name: nginx-container
    image: nginx
    env:
    - name: Organization_token
      valueFrom:
        secretKeyRef:
          name: secret03
          key: |
           root-password
           token
  restartPolicy: Never
